{
 "title": "General Envoy - Universe",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Downstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downstream CPS",
     "type": "timeseries",
     "description": "Average change in amount of downstream connections per minute",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(envoy_http_downstream_cx_total{}[1m])) by (service)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Downstream Active CPS",
     "type": "timeseries",
     "description": "Average change in amount of active downstream connections per minute",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(envoy_http_downstream_cx_active{}[1m])) by (service)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Downstream RPS",
     "type": "timeseries",
     "description": "Average change in amount of downstream requests per minute",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(envoy_http_downstream_rq_total{}[1m])) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Downstream Latency",
     "type": "graph",
     "description": "Average time a downstream request took in ms, divided into 50%, 75%, 99% of the requests.\nFor example 50% of the requests took less then 5ms to serve",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{}[1m])) by (le, service))",
       "legendFormat": "{{service}} 99%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(envoy_http_downstream_rq_time_bucket{}[1m])) by (le, service))",
       "legendFormat": "{{service}} 75%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{}[1m])) by (le, service))",
       "legendFormat": "{{service}} 50%"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream CPS",
     "type": "timeseries",
     "description": "Average change in amount of upstream connections per minute",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_total{}[1m])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Active CPS",
     "type": "timeseries",
     "description": "Average change in amount of upstream active connections per minute",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_active{}[1m])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream RPS",
     "type": "timeseries",
     "description": "Average change in amount of upstream requests per minute",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{}[1m])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Latency",
     "type": "graph",
     "description": "Average time a request took in ms, divided into 50%, 75%, 99% of the requests.\nFor example 50% of the requests took less then 5ms to serve",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{}[1m])) by (le, envoy_cluster_name))",
       "legendFormat": "{{envoy_cluster_name}} 99%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(envoy_cluster_upstream_rq_time_bucket{}[1m])) by (le, envoy_cluster_name))",
       "legendFormat": "{{envoy_cluster_name}} 75%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{}[1m])) by (le, envoy_cluster_name))",
       "legendFormat": "{{envoy_cluster_name}} 50%"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream 2xx Responses rate",
     "type": "timeseries",
     "description": "Per-second average rate of 2XX response increase in a minute",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{envoy_response_code_class=~\"2\"}[1m])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream 3xx Responses rate",
     "type": "timeseries",
     "description": "Per-second average rate of 3XX response increase in a minute",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{envoy_response_code_class=~\"3\"}[1m])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream 4xx Responses rate",
     "type": "timeseries",
     "description": "Per-second average rate of 4XX response increase in a minute",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{envoy_response_code_class=~\"4\"}[1m])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream 5xx Responses rate",
     "type": "timeseries",
     "description": "Per-second average rate of 5XX response increase in a minute",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{envoy_response_code_class=~\"5\"}[1m])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Allocated Memory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_memory_allocated{}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Live Servers",
   "type": "piechart",
   "description": "The amount of envoy servers that are live, meaning not draining",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live{})", "legendFormat": "Live Servers" },
    {
     "expr": "count(envoy_server_live{})-sum(envoy_server_live{})",
     "legendFormat": "Draining Servers"
    }
   ]
  },
  {
   "title": "Clusters Member Health",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total{}) by (pod, envoy_cluster_name)"
    },
    {
     "expr": "envoy_cluster_membership_healthy{}"
    }
   ]
  }
 ]
}