{
 "title": "Echo Service Envoy - Universe",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Echo GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failure Percentage",
   "type": "timeseries",
   "description": "Per pod failure percentage",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_grpc_Echo_failure{}[1m])/increase(envoy_cluster_grpc_Echo_total{}[1m]) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Internal Failure Percentage",
   "type": "timeseries",
   "description": "Per pod failure percentage",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(envoy_cluster_grpc_Echo_13{}[1m])/increase(envoy_cluster_grpc_Echo_total{}[1m]) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "description": "The average change in amount of failures in a minute",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_grpc_Echo_failure{}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}